# Generated by Django 3.1.1 on 2020-11-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20201117_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='Post'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userImage',
            field=models.ImageField(blank=True, default='', upload_to='Profile'),
        ),
    ]
