# Generated by Django 3.1.1 on 2020-11-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20201119_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userImage',
            field=models.ImageField(blank=True, default='default/default.png', upload_to='Profile'),
        ),
    ]
